### ISSUE TITLE
objLoader/obj_parser.h

### ISSUE THREAD

**Issue by fbourigault** [X123M3-256/RCT2RideGenerator#2]
I'm trying to build this project and I'm wondering where `objLoader/obj_parser.h` come from ?

**Comment by X123M3-256** [comment]
Sorry - forgot to add those files to the repository. They are taken from [here](http://kixor.net/dev/objloader/) but I've had to make some alterations to get them to compile as plain C. I've added them to the repository, but the code on the repository is outdated as I'm in the middle of a complete overhaul of the animation system right now - I think the latest version on here works but is missing features. I'll update it again when I've finished this alteration. Also, the code as it stands is rather unstable and prone to segfaults - I'm trying to fix that too.

**Comment by fbourigault** [comment]
Looks like this is fixed since June 22. Thanks
