### ISSUE TITLE
flags off by one

### ISSUE THREAD

**Issue by spacek531** [X123M3-256/RCT2RideGenerator#8]
Currently the vehicle flags value covers the animation type byte and the first 3 of 4 flags bytes, with `extra frames` as the 4th flag byte. I plan to refactor this eventually.

**Comment by X123M3-256** [comment]
This is a known issue. Development started before OpenRCT2 existed, so initially I had to guess what was flags and what wasn't. Since the animation type wasn't known to me at the time I assumed it was part of the flags, and I never updated the code to correct this.
